---
id: kagoshima-rubykaigi01
base_name: infrequent-use-ruby-features
tags:
- ruby
presentation_date: 2019/11/30
version: 2019.11.30
licenses: []
slideshare_id: ruby-199958323
speaker_deck_id: amarizhi-rareteinairubyfalsebian-li-ji-neng
ustream_id:
vimeo_id:
youtube_id:
author:
  markup_language: :markdown
  name: Kazuhiro NISHIYAMA
  email: zn@mbf.nifty.com
  rubygems_user: znz
  slideshare_user: znzjp
  speaker_deck_user: znz
